const dummyProperties = [
  {
    propertyId: 1,
    propertyType: "Villa",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 3,500,000",
    propertyName: "Palm Oasis Villa",
    propertyLocation: "Palm Jumeirah, Dubai",
    propertyBed: 5,
    propertyBath: 6,
    propertySize: "6,000 sqft",
    whatsappButton: "https://wa.me/971500000000",
    callButton: "tel:+971500000000",
    emailButton: "mailto:agent@example.com",
    agentImage: "/agents.png",
    agentName: "John Smith",
    propertyDetailsButton: "/properties/palm-oasis-villa",
    likeButton: "/like/palm-oasis-villa",
  },
  {
    propertyId: 2,
    propertyType: "Apartment",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 1,200,000",
    propertyName: "Downtown Chic Apartment",
    propertyLocation: "Downtown Dubai",
    propertyBed: 2,
    propertyBath: 2,
    propertySize: "1,200 sqft",
    whatsappButton: "https://wa.me/971511111111",
    callButton: "tel:+971511111111",
    emailButton: "mailto:agent2@example.com",
    agentImage: "/agents.png",
    agentName: "Sara Al Nuaimi",
    propertyDetailsButton: "/properties/downtown-chic-apartment",
    likeButton: "/like/downtown-chic-apartment",
  },
  {
    propertyId: 3,
    propertyType: "Townhouse",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 2,100,000",
    propertyName: "Green Community Townhouse",
    propertyLocation: "Dubai Hills Estate",
    propertyBed: 3,
    propertyBath: 4,
    propertySize: "2,800 sqft",
    whatsappButton: "https://wa.me/971522222222",
    callButton: "tel:+971522222222",
    emailButton: "mailto:agent3@example.com",
    agentImage: "/agents.png",
    agentName: "Ali Khan",
    propertyDetailsButton: "/properties/green-community-townhouse",
    likeButton: "/like/green-community-townhouse",
  },
  {
    propertyId: 4,
    propertyType: "Townhouse",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 2,100,000",
    propertyName: "Green Community Townhouse",
    propertyLocation: "Dubai Hills Estate",
    propertyBed: 3,
    propertyBath: 4,
    propertySize: "2,800 sqft",
    whatsappButton: "https://wa.me/971522222222",
    callButton: "tel:+971522222222",
    emailButton: "mailto:agent3@example.com",
    agentImage: "/agents.png",
    agentName: "Ali Khan",
    propertyDetailsButton: "/properties/green-community-townhouse",
    likeButton: "/like/green-community-townhouse",
  },
  {
    propertyId: 5,
    propertyType: "Villa",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 3,500,000",
    propertyName: "Palm Oasis Villa",
    propertyLocation: "Palm Jumeirah, Dubai",
    propertyBed: 5,
    propertyBath: 6,
    propertySize: "6,000 sqft",
    whatsappButton: "https://wa.me/971500000000",
    callButton: "tel:+971500000000",
    emailButton: "mailto:agent@example.com",
    agentImage: "/agents.png",
    agentName: "John Smith",
    propertyDetailsButton: "/properties/palm-oasis-villa",
    likeButton: "/like/palm-oasis-villa",
  },
  {
    propertyId: 6,
    propertyType: "Apartment",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 1,200,000",
    propertyName: "Downtown Chic Apartment",
    propertyLocation: "Downtown Dubai",
    propertyBed: 2,
    propertyBath: 2,
    propertySize: "1,200 sqft",
    whatsappButton: "https://wa.me/971511111111",
    callButton: "tel:+971511111111",
    emailButton: "mailto:agent2@example.com",
    agentImage: "/agents.png",
    agentName: "Sara Al Nuaimi",
    propertyDetailsButton: "/properties/downtown-chic-apartment",
    likeButton: "/like/downtown-chic-apartment",
  },
  {
    propertyId: 7,
    propertyType: "Townhouse",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 2,100,000",
    propertyName: "Green Community Townhouse",
    propertyLocation: "Dubai Hills Estate",
    propertyBed: 3,
    propertyBath: 4,
    propertySize: "2,800 sqft",
    whatsappButton: "https://wa.me/971522222222",
    callButton: "tel:+971522222222",
    emailButton: "mailto:agent3@example.com",
    agentImage: "/agents.png",
    agentName: "Ali Khan",
    propertyDetailsButton: "/properties/green-community-townhouse",
    likeButton: "/like/green-community-townhouse",
  },
  {
    propertyId: 8,
    propertyType: "Townhouse",
    propertyImage: "/home.jpg",
    propertyPrice: "AED 2,100,000",
    propertyName: "Green Community Townhouse",
    propertyLocation: "Dubai Hills Estate",
    propertyBed: 3,
    propertyBath: 4,
    propertySize: "2,800 sqft",
    whatsappButton: "https://wa.me/971522222222",
    callButton: "tel:+971522222222",
    emailButton: "mailto:agent3@example.com",
    agentImage: "/agents.png",
    agentName: "Ali Khan",
    propertyDetailsButton: "/properties/green-community-townhouse",
    likeButton: "/like/green-community-townhouse",
  },
];

export default dummyProperties;
